Update docker build script to enable using template Dockerfiles
Allows for building e.g. conda-based Dockers more easily and without
repetition.

diff --git a/scripts/build_docker_images b/scripts/build_docker_images
--- a/scripts/build_docker_images
+++ b/scripts/build_docker_images
@@ -32,78 +32,83 @@ err() {
 }
 
 build_docker_image() {
-  local dockerfile_path="$1"
-  local docker_context_dir="$2"
+  local build_env_file="$1"
+  local docker_context_dir=$(dirname "${build_env_file}")
   local -a build_args
-  local -a varnames
-  local env_file="${docker_context_dir}/build.env"
 
-  if [[ -s "${env_file}" ]]; then
-    nobuild=$(grep 'NOBUILD=true' "${env_file}" || true)
-    if [[ -n "${nobuild}" ]]; then
+  (
+    # Ensure we're pulling these variables from the build_env_file
+    unset IMAGE_NAME IMAGE_TAG DOCKERFILE NOBUILD CONDA_ENVIRONMENT_TEMPLATE
+
+    set -a
+    . "${build_env_file}"
+    set +a
+
+    IMAGE_NAME=${IMAGE_NAME:-}
+    IMAGE_TAG=${IMAGE_TAG:-}
+    DOCKERFILE=${DOCKERFILE:-}
+    NOBUILD=${NOBUILD:-false}
+    CONDA_ENVIRONMENT_TEMPLATE=${CONDA_ENVIRONMENT_TEMPLATE:-}
+
+    if [[ "${NOBUILD}" == "true" ]]; then
       log "No-build set for docker context [${docker_context_dir}]; skipping"
       return
     fi
-    while read -r build_arg || [[ -n "${build_arg}" ]]; do
-      varname=$(echo "${build_arg}" | cut -d = -f 1)
-      value=$(echo "${build_arg}" | cut -d = -f 2 | envsubst)
 
-      set +u
-      if [[ -n "${!varname}" ]]; then
-        err "[WARN] Overwriting existing env variable [${varname}], value [${!varname}] with value [${value}]"
-      fi
-      set -u
-
-      export "${varname}=${value}"
-
-      build_args+=(--build-arg "${varname}=${value}")
-      varnames+=("${varname}")
-    done < "${env_file}"
-  else
-    err "[ERROR] No env file found for docker context [${docker_context_dir}]"
-    err "[ERROR] Minimally define IMAGE_NAME=xxx and IMAGE_TAG=xxx in [${env_file}] and try again."
-    exit 1
-  fi
-
-  local image_name
-  local image_tag
-  for varname in "${varnames[@]}"; do
-    if [[ "${varname}" == "IMAGE_NAME" ]]; then
-      image_name=${!varname}
-    elif [[ "${varname}" == "IMAGE_TAG" ]]; then
-      image_tag=${!varname}
+    # Find the Dockerfile, either in the same directory as the build.env file or using the DOCKERFILE variable from build.env
+    if [[ -z "${DOCKERFILE}" ]]; then
+      dockerfile=$(find "${docker_context_dir}" -type f -name Dockerfile)
+    else
+      dockerfile="${docker_context_dir}/${DOCKERFILE}"
     fi
-    unset "${varname}"
-  done
+    if [[ ! -s "${dockerfile}" ]]; then
+      err "[ERROR] Dockerfile not found; either create ${docker_context_dir}/Dockerfile or define the DOCKERFILE variable in ${build_env_file}"
+      exit 1
+    fi
 
-  set +u
-  if [[ -z "${image_name}" ]]; then
-    err "[ERROR] No IMAGE_NAME defined for docker context [${docker_context_dir}]"
-    err "[ERROR] Set IMAGE_NAME in [${env_file}] and try again."
-    exit 1
-  fi
+    # Ensure that at minimum IMAGE_NAME and IMAGE_TAG are defined
+    if [[ -z "${IMAGE_NAME}" ]]; then
+      err "[ERROR] No IMAGE_NAME defined for docker context [${docker_context_dir}]"
+      err "[ERROR] Set IMAGE_NAME in [${build_env_file}] and try again."
+      exit 1
+    fi
+    if [[ -z "${IMAGE_TAG}" ]]; then
+      err "[ERROR] No IMAGE_TAG defined for docker context [${docker_context_dir}]"
+      err "[ERROR] Set IMAGE_TAG in [${build_env_file}] and try again."
+      exit 1
+    fi
 
-  if [[ -z "${image_tag}" ]]; then
-    err "[ERROR] No IMAGE_TAG defined for docker context [${docker_context_dir}]"
-    err "[ERROR] Set IMAGE_TAG in [${env_file}] and try again."
-    exit 1
-  fi
-  set -u
+    # Make all varaiables defined in build.env available as build args
+    while read -r varname || [[ -n "${varname}" ]]; do
+      build_args+=(--build-arg "${varname}=${!varname}")
+    done < <(grep -v -e '^#' -e '^$' "${build_env_file}" | cut -d '=' -f 1)
 
-  local tagged_image="${CONTAINER_REGISTRY:+"${CONTAINER_REGISTRY}/"}${image_name}:${image_tag}"
-  log "Building ${tagged_image}"
+    # If a conda environment template is specified, generate a populated version of the file to be copied into the image
+    conda_environment_template="${docker_context_dir}/${CONDA_ENVIRONMENT_TEMPLATE}"
+    if [[ -n "${CONDA_ENVIRONMENT_TEMPLATE}" ]] && [[ -s "${conda_environment_template}" ]]; then
+      populated_conda_environment=${docker_context_dir}/${IMAGE_NAME}.populated.yaml
 
-  docker build \
-    --rm \
-    "${build_args[@]}" \
-    -t "${tagged_image}" \
-    -f "${dockerfile_path}" \
-    "${docker_context_dir}"
+      log "Generating populated conda environment [${populated_conda_environment}]"
+      envsubst \
+        < "${conda_environment_template}" \
+        > "${populated_conda_environment}"
+    fi
 
-  if [[ "${PUSH_IMAGES}" == 'true' ]]; then
-    log "Pushing ${tagged_image}"
-    docker push "${tagged_image}"
-  fi
+    tagged_image="${CONTAINER_REGISTRY:+"${CONTAINER_REGISTRY}/"}${IMAGE_NAME}:${IMAGE_TAG}"
+    log "Building ${tagged_image}"
+
+    docker build \
+      --rm \
+      "${build_args[@]}" \
+      -t "${tagged_image}" \
+      -f "${dockerfile}" \
+      "${docker_context_dir}"
+
+    if [[ "${PUSH_IMAGES}" == 'true' ]]; then
+      log "Pushing ${tagged_image}"
+      docker push "${tagged_image}"
+    fi
+  )
 }
 
 while getopts "hd:c:p" OPTION; do
@@ -121,13 +126,12 @@ PUSH_IMAGES=${PUSH_IMAGES:-'false'}
 
 readonly DOCKER_CONTEXT_DIR CONTAINER_REGISTRY PUSH_IMAGES
 
-IMAGES_TO_BUILD=$(find "${DOCKER_CONTEXT_DIR}" -type f -name Dockerfile)
+IMAGES_TO_BUILD=$(find "${DOCKER_CONTEXT_DIR}" -type f -name build.env)
 if [[ "${#IMAGES_TO_BUILD}" -eq 0 ]]; then
   usage
   exit
 fi
 
-while read -r dockerfile_path; do
-  docker_context_dir=$(dirname "${dockerfile_path}")
-  build_docker_image "${dockerfile_path}" "${docker_context_dir}"
+while read -r build_env_file; do
+  build_docker_image "${build_env_file}"
 done <<< "${IMAGES_TO_BUILD}"
